/* DrillTracker rig data. Edit this file to refresh the data, then run
     node scripts/validate.js
   before committing. See README.md for the field definitions. */

/* The date the data was last checked. Every status, "time left" and backlog
   figure in the app is computed as of this date, not the viewer's clock. */
const DATA_AS_OF = '2026-10-04';

const RIG_DATA = [
  {
    id: "rig-001",
    name: "Deepwater Titan",
    contractor: "Transocean",
    owner: null,
    type: "Drillship",
    generation: "8th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1700,
    buildYear: 2023,
    region: "Gulf of America",
    country: "United States",
    lat: 28.2,
    lng: -89.5,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Chevron", start: "Apr 2023", end: "Apr 2028", dayRate: 463000, firmness: "firm" }
    ],
    note: "Chevron USGOM; firm to Apr 2028 at $463k/day (Aug 5, 2026 FSR; $462k in May, the change is cost escalation)."
  },
  {
    id: "rig-002",
    name: "Deepwater Atlas",
    contractor: "Transocean",
    owner: null,
    type: "Drillship",
    generation: "8th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1700,
    buildYear: 2022,
    region: "Gulf of America",
    country: "United States",
    lat: 28.5,
    lng: -88.8,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Beacon Offshore", start: "Aug 2025", end: "Oct 2026", dayRate: 580000, firmness: "firm", note: "term began Aug 2025 at $505k; $580k rate period from Aug 2026" },
      { customer: "Beacon Offshore", start: "Oct 2026", end: "Dec 2026", dayRate: 650000, firmness: "option", note: "contingent" },
      { customer: "Beacon Offshore", start: "Dec 2026", end: "Dec 2026", dayRate: 580000, firmness: "firm" },
      { customer: "Beacon Offshore", start: "Dec 2026", end: "Feb 2027", dayRate: 650000, firmness: "option", note: "contingent" },
      { customer: "Beacon Offshore", start: "Feb 2027", end: "Feb 2027", dayRate: 580000, firmness: "firm" },
      { customer: "Beacon Offshore", start: "Feb 2027", end: "Jul 2027", dayRate: 505000, firmness: "firm" },
      { customer: "bp", start: "Jun 2028", end: "Jun 2030", dayRate: 635000, firmness: "firm" }
    ],
    note: "Beacon USGOM: firm periods at $580k and $505k/day, with contingent periods at $650k/day, running to Jul 2027 (Aug 5, 2026 FSR). Then bp fixtures at $635k/day from Jun 2028 to Jun 2030."
  },
  {
    id: "rig-003",
    name: "Deepwater Aquila",
    contractor: "Transocean",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1400,
    buildYear: 2024,
    region: "South America",
    country: "Brazil",
    lat: -22.8,
    lng: -40.2,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Petrobras", start: "Jun 2024", end: "Dec 2026", dayRate: 438000, firmness: "firm" },
      { customer: "Petrobras", start: "Jan 2027", end: "Jun 2028", dayRate: 443000, firmness: "firm", note: "365-day extension" }
    ],
    note: "Petrobras Brazil pre-salt; 365-day extension takes firm work to Jun 2028. Aug 5, 2026 FSR: $438k/day to Dec 2026, then $443k/day Jan 2027 to Jun 2028."
  },
  {
    id: "rig-004",
    name: "Deepwater Poseidon",
    contractor: "Transocean",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1400,
    buildYear: 2018,
    region: "Gulf of America",
    country: "United States",
    lat: 28.8,
    lng: -89.2,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Shell", start: "Sep 2018", end: "Feb 2028", dayRate: 501000, firmness: "firm" }
    ],
    note: "Long-term Shell USGOM contract firm to Feb 2028 at $501k/day (Aug 5, 2026 FSR)."
  },
  {
    id: "rig-005",
    name: "Deepwater Pontus",
    contractor: "Transocean",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1400,
    buildYear: 2017,
    region: "Gulf of America",
    country: "United States",
    lat: 28.4,
    lng: -89.8,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Shell", start: "Oct 2017", end: "Oct 2027", dayRate: 499000, firmness: "firm" }
    ],
    note: "Long-term Shell USGOM contract firm to Oct 2027 at $499k/day (Aug 5, 2026 FSR)."
  },
  {
    id: "rig-006",
    name: "Deepwater Conqueror",
    contractor: "Transocean",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1400,
    buildYear: 2016,
    region: "Gulf of America",
    country: "United States",
    lat: 27.9,
    lng: -90.1,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026; award, Sep 15, 2026",
    asOf: "2026-09-15",
    contracts: [
      { customer: null, start: "Oct 2025", end: "Jan 2027", dayRate: 530000, firmness: "firm" },
      { customer: null, start: "Feb 2027", end: "Jul 2027", dayRate: null, firmness: "firm", note: "Equatorial Guinea, two wells, ~170 days, ~$80M; months estimated from \"2027, in direct continuation\"" }
    ],
    note: "Undisclosed US Gulf operator; two-well extension (Aug 5, 2026 FSR) keeps the rig working to ~Jan 2027 at $530k/day. Sep 15, 2026 award: two-well, ~170-day Equatorial Guinea contract (~$80M, undisclosed operator) commencing 2027 in direct continuation."
  },
  {
    id: "rig-007",
    name: "Deepwater Invictus",
    contractor: "Transocean",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1400,
    buildYear: 2014,
    region: "Gulf of America",
    country: "United States",
    lat: 28.1,
    lng: -88.4,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "bp", start: "Apr 2025", end: "Apr 2028", dayRate: 485000, firmness: "firm" }
    ],
    note: "3-year bp USGOM campaign firm to Apr 2028 at $485k/day"
  },
  {
    id: "rig-008",
    name: "Deepwater Asgard",
    contractor: "Transocean",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1400,
    buildYear: 2014,
    region: "Mediterranean & Black Sea",
    country: null,
    lat: 33,
    lng: 34.5,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: null, start: "Dec 2026", end: "Dec 2027", dayRate: 405000, firmness: "firm", note: "Eastern Mediterranean, five wells, ~$158M" }
    ],
    note: "US Gulf work for an undisclosed operator ended ~Jun 2026. Next: five-well Eastern Mediterranean campaign (~$158M, ~390 days, undisclosed operator), shown in the Aug 5, 2026 FSR as Dec 2026-Dec 2027 at $405k/day after ~20 days of contract preparation. Plotted at the Mediterranean work area; current position unconfirmed."
  },
  {
    id: "rig-009",
    name: "Deepwater Thalassa",
    contractor: "Transocean",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1400,
    buildYear: 2016,
    region: "Gulf of America",
    country: "Mexico",
    lat: 19.4,
    lng: -92.5,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Woodside", start: "Mar 2026", end: "Feb 2029", dayRate: 495000, firmness: "firm" }
    ],
    note: "Multi-year Woodside campaign offshore Mexico firm to Feb 2029 at $495k/day"
  },
  {
    id: "rig-010",
    name: "Deepwater Skyros",
    contractor: "Transocean",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2013,
    region: "West Africa",
    country: "Côte d'Ivoire",
    lat: 4.8,
    lng: -4.2,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Murphy Oil", start: "Jun 2026", end: "Sep 2026", dayRate: 361000, firmness: "firm" },
      { customer: "Murphy Oil", start: "Oct 2026", end: "Nov 2026", dayRate: 361000, firmness: "option", note: "priced option; exercise not confirmed" },
      { customer: null, start: "Apr 2027", end: "Mar 2028", dayRate: null, firmness: "firm", note: "Australia; priced options to Jul 2030" }
    ],
    note: "Murphy Cote d'Ivoire one-well extension at $361k/day, firm to ~Sep 2026 with a priced option at the same rate to Nov 2026 (Aug 5, 2026 FSR; option exercise not yet confirmed). Next firm work: undisclosed-operator Australia campaign ~Apr 2027-Mar 2028 with priced options to Jul 2030."
  },
  {
    id: "rig-011",
    name: "Deepwater Corcovado",
    contractor: "Transocean",
    owner: null,
    type: "Drillship",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2011,
    region: "South America",
    country: "Brazil",
    lat: -23.1,
    lng: -41.5,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Petrobras", start: "Sep 2023", end: "Dec 2026", dayRate: 379000, firmness: "firm" },
      { customer: "Petrobras", start: "Jan 2027", end: "Nov 2030", dayRate: 390000, firmness: "firm", note: "1,156-day extension" }
    ],
    note: "New 1,156-day Petrobras extension; Aug 5, 2026 FSR shows $379k/day to Dec 2026, then $390k/day to Nov 2030."
  },
  {
    id: "rig-012",
    name: "Deepwater Mykonos",
    contractor: "Transocean",
    owner: null,
    type: "Drillship",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2011,
    region: "South America",
    country: "Brazil",
    lat: -22.4,
    lng: -39.8,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "bp", start: "Sep 2026", end: "Jun 2027", dayRate: 426000, firmness: "firm" }
    ],
    note: "bp Brazil campaign Sep 2026 to Jun 2027 at $426k/day, after 80 days out of service for contract preparation (May to Aug 2026), per the Aug 5, 2026 FSR."
  },
  {
    id: "rig-013",
    name: "Deepwater Orion",
    contractor: "Transocean",
    owner: null,
    type: "Drillship",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2011,
    region: "South America",
    country: "Brazil",
    lat: -22.6,
    lng: -40.5,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Petrobras", start: "Mar 2024", end: "Dec 2026", dayRate: 375000, firmness: "firm" },
      { customer: "Petrobras", start: "Jan 2027", end: "Mar 2030", dayRate: 390000, firmness: "firm", note: "1,095-day extension" }
    ],
    note: "New 1,095-day Petrobras extension; Aug 5, 2026 FSR shows $375k/day to Dec 2026, then $390k/day to Mar 2030."
  },
  {
    id: "rig-014",
    name: "Dhirubhai Deepwater KG1",
    contractor: "Transocean",
    owner: null,
    type: "Drillship",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2009,
    region: "Asia Pacific",
    country: "India",
    lat: 16.8,
    lng: 82.2,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Reliance Industries", start: "Aug 2026", end: "Mar 2028", dayRate: 410000, firmness: "firm" }
    ],
    note: "ONGC contract ended Jul 2026; ~70 days out of service for contract preparation, then the Reliance KG Basin program at $410k/day from ~Aug 2026 to Mar 2028 (six wells plus an exercised four-well option) with further priced options, per the Aug 5, 2026 FSR."
  },
  {
    id: "rig-015",
    name: "Petrobras 10000",
    contractor: "Transocean",
    owner: null,
    type: "Drillship",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2009,
    region: "South America",
    country: "Brazil",
    lat: -23.4,
    lng: -42,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Petrobras", start: "Oct 2025", end: "Oct 2026", dayRate: 416000, firmness: "firm" },
      { customer: "Petrobras", start: "Oct 2026", end: "Oct 2027", dayRate: 428000, firmness: "firm" },
      { customer: "Petrobras", start: "Oct 2027", end: "Oct 2028", dayRate: 441000, firmness: "firm" },
      { customer: "Petrobras", start: "Oct 2028", end: "Aug 2029", dayRate: 454000, firmness: "firm" }
    ],
    note: "Multi-year escalating Petrobras contract, stepping each October (Aug 5, 2026 FSR): $416k to Oct 2026, $428k, $441k, then $454k/day through Aug 2029."
  },
  {
    id: "rig-016",
    name: "Transocean Norge",
    contractor: "Transocean",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 10000,
    hookload_tons: 1250,
    buildYear: 2017,
    region: "North Sea",
    country: "Norway",
    lat: 61.2,
    lng: 3.8,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Harbour Energy / OMV", start: "Jan 2026", end: "Jan 2028", dayRate: 472000, firmness: "firm" },
      { customer: "Harbour Energy", start: "Jan 2028", end: "Nov 2028", dayRate: 513000, firmness: "firm", note: "five wells" },
      { customer: "Harbour Energy", start: "Nov 2028", end: "Mar 2029", dayRate: null, firmness: "option", note: "three one-well priced options" }
    ],
    note: "Harbour/OMV NCS contract to Jan 2028 at $472k/day, then a five-well Harbour Energy program Jan to Nov 2028 at $513k/day with three one-well priced options to Mar 2029 (Aug 5, 2026 FSR)."
  },
  {
    id: "rig-017",
    name: "Transocean Spitsbergen",
    contractor: "Transocean",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2010,
    region: "North Sea",
    country: "Norway",
    lat: 62,
    lng: 4.5,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Equinor", start: "Mar 2026", end: "Mar 2027", dayRate: 413000, firmness: "firm" },
      { customer: "Equinor", start: "Mar 2027", end: "Nov 2027", dayRate: 515000, firmness: "firm" }
    ],
    note: "Equinor NCS campaign; Aug 5, 2026 FSR shows $413k/day to Mar 2027, then $515k/day to Nov 2027."
  },
  {
    id: "rig-018",
    name: "Transocean Barents",
    contractor: "Transocean",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2009,
    region: "Mediterranean & Black Sea",
    country: "Romania",
    lat: 44.1,
    lng: 30.8,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "OMV Petrom", start: "Mar 2025", end: "Sep 2026", dayRate: 482000, firmness: "firm" },
      { customer: "OMV Petrom", start: "Sep 2026", end: "Feb 2027", dayRate: 498000, firmness: "firm" },
      { customer: "Vår Energi", start: "Jul 2027", end: "Jul 2030", dayRate: 467000, firmness: "firm", note: "Norway, 1,095 days" },
      { customer: "Vår Energi", start: "Jul 2030", end: "Jul 2034", dayRate: null, firmness: "option", note: "priced options" }
    ],
    note: "OMV Petrom Romania at $482k/day, then $498k/day from Sep 2026 to Feb 2027. About 135 days of mobilization and contract preparation follow, then a 1,095-day Vår Energi Norway contract at $467k/day from Jul 2027 to Jul 2030, with priced options to 2034 (Aug 5, 2026 FSR)."
  },
  {
    id: "rig-019",
    name: "Transocean Enabler",
    contractor: "Transocean",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 7500,
    hookload_tons: 750,
    buildYear: 2016,
    region: "North Sea",
    country: "Norway",
    lat: 60.5,
    lng: 3.2,
    position: "area",
    statusOverride: null,
    source: "Transocean fleet status report; Equinor award, Jun 30, 2026",
    asOf: "2026-06-30",
    contracts: [
      { customer: "Equinor", start: "Jul 2024", end: "Oct 2026", dayRate: 420000, firmness: "firm" },
      { customer: "Equinor", start: "Nov 2026", end: "Mar 2028", dayRate: 460000, firmness: "firm" },
      { customer: "Equinor", start: "Q1 2028", end: "Q1 2031", dayRate: 399000, firmness: "conditional", note: "base rate; conditional on licence approvals" }
    ],
    note: "Equinor NCS; FSR shows $420k/day to Oct 2026 then $460k/day to Mar 2028, with an out-of-service period in Apr-May 2026; follow-on three-year Equinor program from Q1 2028 announced Jun 30, 2026 (part of Equinor's $1B+ multi-rig agreement at $399k/day base, conditional on license approvals)"
  },
  {
    id: "rig-020",
    name: "Transocean Encourage",
    contractor: "Transocean",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 7500,
    hookload_tons: 750,
    buildYear: 2016,
    region: "North Sea",
    country: "Norway",
    lat: 61.5,
    lng: 4,
    position: "area",
    statusOverride: null,
    source: "Equinor award, Jun 30, 2026",
    asOf: "2026-06-30",
    contracts: [
      { customer: null, start: "Jan 2026", end: "Mar 2027", dayRate: 495000, firmness: "firm" },
      { customer: null, start: "Apr 2027", end: "Mar 2028", dayRate: 421000, firmness: "firm" },
      { customer: "Equinor", start: "Q1 2028", end: "Q1 2030", dayRate: 399000, firmness: "conditional", note: "base rate; conditional on licence approvals" }
    ],
    note: "Undisclosed NCS operator at $495k/day to Mar 2027 then $421k/day to Mar 2028; follow-on two-year Equinor program from Q1 2028 announced Jun 30, 2026 ($1B+ Equinor agreement, $399k/day base, conditional on license approvals)"
  },
  {
    id: "rig-021",
    name: "Transocean Endurance",
    contractor: "Transocean",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 7500,
    hookload_tons: 750,
    buildYear: 2015,
    region: "Asia Pacific",
    country: "Australia",
    lat: -19.8,
    lng: 116.5,
    position: "area",
    statusOverride: null,
    source: "Equinor award, Jun 30, 2026",
    asOf: "2026-06-30",
    contracts: [
      { customer: "Woodside", start: "Feb 2026", end: "Aug 2026", dayRate: 390000, firmness: "firm" },
      { customer: "Woodside", start: "Sep 2026", end: "Oct 2026", dayRate: 419000, firmness: "firm" },
      { customer: "Equinor", start: "Q2 2027", end: "Q2 2029", dayRate: 399000, firmness: "conditional", note: "Norway; base rate; conditional on licence approvals" }
    ],
    note: "Woodside offshore Australia at $390k/day to Aug 2026 then $419k/day to Oct 2026; Jun 30, 2026 award: two-year Equinor Norway program commencing Q2 2027 at $399k/day base - rig to mobilize from Australia to the NCS (part of Equinor's $1B+ multi-rig agreement, conditional on license approvals)"
  },
  {
    id: "rig-022",
    name: "Transocean Equinox",
    contractor: "Transocean",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 7500,
    hookload_tons: 750,
    buildYear: 2015,
    region: "Asia Pacific",
    country: "Australia",
    lat: -38.75,
    lng: 142.85,
    position: "field",
    statusOverride: null,
    source: "operator well updates, Sep 2026",
    asOf: "2026-09",
    contracts: [
      { customer: "Amplitude Energy", start: "Aug 2026", end: "Dec 2026", dayRate: 540000, firmness: "firm", note: "Otway consortium (Amplitude, Beach, ConocoPhillips)" },
      { customer: "Santos", start: "Q2 2027", end: "Q2 2027", dayRate: null, firmness: "firm", note: "two wells, ~90 days, ~$36M, plus options" }
    ],
    note: "Otway Basin, offshore Victoria, for the Amplitude/Beach/ConocoPhillips consortium at $540k/day: Juliet-1 spudded Aug 22, 2026 and was completed late Sep 2026 as a gas discovery; moving to Annie-2 with an optional Nestor well, to ~Dec 2026. Next: two-well Santos contract (~$36M, ~90 days, plus options) from Q2 2027."
  },
  {
    id: "rig-023",
    name: "West Auriga",
    contractor: "Seadrill",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2013,
    region: "South America",
    country: "Brazil",
    lat: -22.2,
    lng: -39.4,
    position: "area",
    statusOverride: null,
    source: "Seadrill fleet status report, Aug 10, 2026",
    asOf: "2026-08-10",
    contracts: [
      { customer: "Petrobras", start: "Dec 2024", end: "Nov 2027", dayRate: null, firmness: "firm" }
    ],
    note: "Petrobras Búzios/Santos Basin firm contract, Dec 2024 to Nov 2027 (~$577M total value at signing, incl. mobilization and services). Day rate undisclosed; the 2026 fleet status reports list no options."
  },
  {
    id: "rig-024",
    name: "West Neptune",
    contractor: "Seadrill",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2014,
    region: "Gulf of America",
    country: "United States",
    lat: 27.5,
    lng: -90.5,
    position: "area",
    statusOverride: null,
    source: "Seadrill fleet status report, Aug 10, 2026",
    asOf: "2026-08-10",
    contracts: [
      { customer: "LLOG", start: "May 2026", end: "Oct 2026", dayRate: null, firmness: "firm", note: "bridging term, ~120 days, ~$48M" },
      { customer: "LLOG", start: "Oct 2026", end: "Oct 2027", dayRate: null, firmness: "firm", note: "365-day extension" }
    ],
    note: "LLOG (Harbour Energy subsidiary): a ~120-day bridging term (~$48M) from May 2026, then the 365-day extension from Oct 2026 to Oct 2027 (Aug 10, 2026 FSR; the Apr 22, 2026 award said Sep 2026). Part of a ~$260M combined Neptune and Vela award. Day rate undisclosed."
  },
  {
    id: "rig-025",
    name: "West Vela",
    contractor: "Seadrill",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2013,
    region: "Gulf of America",
    country: "United States",
    lat: 28.3,
    lng: -89.6,
    position: "area",
    statusOverride: null,
    source: "Seadrill Q2 2026 results, Aug 2026",
    asOf: "2026-08",
    contracts: [
      { customer: "LLOG", start: "Aug 2026", end: "Jun 2027", dayRate: null, firmness: "firm" },
      { customer: "Talos Energy", start: "Jun 2027", end: "Jun 2028", dayRate: null, firmness: "firm", note: "customer per trade press; ~$161M excl. services" }
    ],
    note: "LLOG (Harbour Energy) 270-day program Aug 2026-~Jun 2027 (part of the ~$260M Apr 2026 Neptune+Vela award). Q2 2026 results (Aug 2026) added a one-year US Gulf follow-on from Jun 2027 (~$161M excl. services, to ~Jun 2028), reported by trade press as Talos Energy. Day rate undisclosed."
  },
  {
    id: "rig-026",
    name: "West Jupiter",
    contractor: "Seadrill",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2014,
    region: "South America",
    country: "Brazil",
    lat: -23.5,
    lng: -41,
    position: "area",
    statusOverride: null,
    source: "Seadrill fleet status report, Aug 10, 2026",
    asOf: "2026-08-10",
    contracts: [
      { customer: "Petrobras", start: "Mar 2026", end: "Mar 2029", dayRate: null, firmness: "firm" }
    ],
    note: "Petrobras Brazil multi-year program, Mar 2026 to Mar 2029 (~$525M total value at signing). Day rate undisclosed."
  },
  {
    id: "rig-027",
    name: "West Saturn",
    contractor: "Seadrill",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2014,
    region: "South America",
    country: "Brazil",
    lat: -22.9,
    lng: -40.8,
    position: "area",
    statusOverride: null,
    source: "Seadrill fleet status report, Aug 10, 2026",
    asOf: "2026-08-10",
    contracts: [
      { customer: "Equinor", start: "Oct 2022", end: "Oct 2027", dayRate: null, firmness: "firm", note: "priced options to Oct 2030" }
    ],
    note: "Equinor Brazil; a one-year priced option exercised in Jan 2026 extends firm work from Oct 2026 to Oct 2027, with further priced options through Oct 2030 (Aug 10, 2026 FSR). Day rate undisclosed."
  },
  {
    id: "rig-028",
    name: "West Polaris",
    contractor: "Seadrill",
    owner: null,
    type: "Drillship",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2008,
    region: "South America",
    country: "Brazil",
    lat: -22,
    lng: -39.6,
    position: "area",
    statusOverride: null,
    source: "Seadrill fleet status report, Aug 10, 2026",
    asOf: "2026-08-10",
    contracts: [
      { customer: "Petrobras", start: "Apr 2026", end: "Mar 2027", dayRate: 413400, firmness: "firm" },
      { customer: "Petrobras", start: "Apr 2027", end: "Jan 2028", dayRate: 459400, firmness: "firm" },
      { customer: "Petrobras", start: "Jan 2028", end: "Jan 2031", dayRate: 441500, firmness: "firm", note: "1,095-day extension, ~$480M" }
    ],
    note: "Petrobras Búzios/Santos Basin. Aug 10, 2026 FSR: $413,400/day Apr 2026 to Mar 2027, $459,400/day to Jan 15, 2028, then the 1,095-day extension (~$480M, awarded Apr 6, 2026) at $441,500/day to Jan 15, 2031. Rates are subject to foreign-exchange fluctuation."
  },
  {
    id: "rig-029",
    name: "West Tellus",
    contractor: "Seadrill",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2013,
    region: "South America",
    country: "Brazil",
    lat: -25,
    lng: -42.6,
    position: "area",
    statusOverride: null,
    source: "Seadrill Q2 2026 results",
    asOf: "2026-08",
    contracts: [
      { customer: "Petrobras", start: "Jun 2026", end: "Jun 2029", dayRate: null, firmness: "firm" }
    ],
    note: "Petrobras 1,095-day Sepia/Atapu (Santos Basin) contract (~$498M incl. services, plus ~$41M mob fee) commenced Jun 2026 at materially higher rates than the prior program; firm to ~Jun 2029 per Q2 2026 results/10-Q. Day rate undisclosed."
  },
  {
    id: "rig-030",
    name: "West Capella",
    contractor: "Seadrill",
    owner: null,
    type: "Drillship",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2008,
    region: "Asia Pacific",
    country: "Malaysia",
    lat: 4.6,
    lng: 112.4,
    position: "area",
    statusOverride: null,
    source: "Seadrill Q2 2026 results",
    asOf: "2026-08",
    contracts: [
      { customer: "PTTEP", start: "Mar 2026", end: "Aug 2027", dayRate: null, firmness: "firm" }
    ],
    note: "PTTEP Malaysia 440-day program (~$157M) commenced ~Mar 2026 offshore Sarawak; Aug 2026 Q2 results added a ~75-day PTTEP extension (~$26M) committing the rig into Aug 2027. Day rate undisclosed."
  },
  {
    id: "rig-031",
    name: "Sevan Louisiana",
    contractor: "Seadrill",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2013,
    region: "Gulf of America",
    country: "United States",
    lat: 28.66,
    lng: -90.03,
    position: "ais",
    statusOverride: null,
    source: "Seadrill Q2 2026 results; AIS, Sep 18, 2026",
    asOf: "2026-09-18",
    contracts: [],
    note: "After Walter Oil & Gas, Guardian and LLOG/Harbour work in H1 2026, Q2 2026 results (Aug 2026) added ~45 days of Harbour Energy (LLOG) work in direct continuation into Aug 2026. Management cited limited visibility for the rest of 2026 and no follow-on has been announced; AIS (Sep 18, 2026) still shows the rig in the US Gulf, so an unannounced short job is possible. Sevan 650 design."
  },
  {
    id: "rig-032",
    name: "West Elara",
    contractor: "Seadrill",
    owner: null,
    type: "Jackup",
    generation: null,
    jackupClass: "Modern",
    environment: null,
    waterDepth_ft: 400,
    hookload_tons: 450,
    buildYear: 2011,
    region: "North Sea",
    country: "Norway",
    lat: 59.8,
    lng: 2.8,
    position: "area",
    statusOverride: null,
    source: "Seadrill fleet status report, Aug 10, 2026",
    asOf: "2026-08-10",
    contracts: [
      { customer: "Equinor", start: "Sep 2026", end: "Dec 2027", dayRate: null, firmness: "firm", note: "accommodation, ~$78M incl. mobilization; three 3-month priced options" }
    ],
    note: "Equinor NCS accommodation contract, Sep 2026 to Dec 2027 (~$78M incl. mobilization), with three 3-month priced options (Aug 10, 2026 FSR; Jan 21, 2026 award). The previous ConocoPhillips contract ended Aug 2026. Day rate undisclosed."
  },
  {
    id: "rig-033",
    name: "Sonangol Libongos",
    contractor: "Sonadrill",
    owner: "Sonangol",
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2019,
    region: "West Africa",
    country: "Angola",
    lat: -7.5,
    lng: 12,
    position: "area",
    statusOverride: null,
    source: "Seadrill fleet status report, Aug 10, 2026",
    asOf: "2026-08-10",
    contracts: [
      { customer: "Azule Energy", start: "Q3 2025", end: "Feb 2027", dayRate: null, firmness: "firm", note: "~525-day firm term" },
      { customer: "Azule Energy", start: "Mar 2027", end: "Jan 2030", dayRate: null, firmness: "option", note: "priced options" }
    ],
    note: "Azule Energy Angola contract with a ~525-day firm term from Q3 2025 to Feb 2027, plus priced options through Jan 2030 (Aug 25, 2025 award; Aug 10, 2026 FSR). Owned by Sonangol and bareboat-chartered into Sonadrill, the Seadrill/Sonangol JV; Seadrill earns a management fee, not a day rate."
  },
  {
    id: "rig-034",
    name: "Sonangol Quenguela",
    contractor: "Sonadrill",
    owner: "Sonangol",
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2019,
    region: "West Africa",
    country: "Angola",
    lat: -7.8,
    lng: 11.5,
    position: "area",
    statusOverride: null,
    source: "Seadrill fleet status report, Aug 10, 2026",
    asOf: "2026-08-10",
    contracts: [
      { customer: "TotalEnergies", start: "May 2024", end: "Jul 2028", dayRate: null, firmness: "firm", note: "includes a seven-well (~480-day) option exercised in 2026" }
    ],
    note: "TotalEnergies Angola ultra-deepwater drillship. A seven-well (~480-day) priced option exercised in Mar 2026 commits the rig to Jul 2028 (Aug 10, 2026 FSR; the Mar 16, 2026 release said Jun 2028). Owned by Sonangol and bareboat-chartered into Sonadrill; Seadrill earns a management fee, not a day rate."
  },
  {
    id: "rig-035",
    name: "West Gemini",
    contractor: "Sonadrill",
    owner: "Seadrill",
    type: "Drillship",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2010,
    region: "West Africa",
    country: "Angola",
    lat: -6.8,
    lng: 11.8,
    position: "area",
    statusOverride: null,
    source: "Seadrill fleet status report, Aug 10, 2026; Q2 2026 call",
    asOf: "2026-08-10",
    contracts: [
      { customer: "Sonangol E&P", start: "Feb 2026", end: "Nov 2026", dayRate: null, firmness: "firm" }
    ],
    note: "Sonangol E&P ~284-day Angola campaign, Feb 2026 to ~Nov 2026. Seadrill-owned and bareboat-chartered into Sonadrill; Seadrill earns a management fee, not a day rate. On the Aug 10, 2026 Q2 call management said the rig rolls off later in 2026 with no follow-on yet and is being marketed in West Africa, where most campaigns start in H1 2027."
  },
  {
    id: "rig-036",
    name: "Noble Globetrotter I",
    contractor: "Noble Corporation",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2013,
    region: "West Africa",
    country: "Spain (Canary Islands)",
    lat: 28.95,
    lng: -13.52,
    position: "ais",
    statusOverride: null,
    source: "AIS, early Sep 2026",
    asOf: "2026-09",
    contracts: [],
    note: "Idle since the OMV Petrom Bulgaria (Black Sea) campaign ended in Q2 2026. Arrived at Arrecife, Lanzarote (Canary Islands) ~Jun 19, 2026 for a 4-6 month stay for maintenance and inspections; AIS still showed it moored there in early Sep 2026. Noble is bidding it for intervention/specialist work; trade press calls it a divestment candidate if no work materializes."
  },
  {
    id: "rig-037",
    name: "Noble Sam Croft",
    contractor: "Noble Corporation",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2014,
    region: "South America",
    country: "Guyana",
    lat: 7,
    lng: -57.5,
    position: "area",
    statusOverride: null,
    source: "Noble fleet status report, Jul 27, 2026; Drilling Contractor, Sep 28, 2026",
    asOf: "2026-09-28",
    contracts: [
      { customer: "ExxonMobil", start: "Apr 2019", end: "Feb 2029", dayRate: null, firmness: "firm", note: "market-based rate under the ExxonMobil Commercial Enabling Agreement, reset each Jan 1 and Jul 1" }
    ],
    note: "ExxonMobil Guyana, Stabroek block, under the Commercial Enabling Agreement. The rate is market-based and not disclosed; it resets each Jan 1 and Jul 1 after a Mar 1, 2026 pricing reset. On Jan 26, 2026 ExxonMobil added two rig-years across the four Noble rigs, taking each to Feb 2029. Back at work on the Whiptail WT_4i02 well from Sep 23, 2026 (Drilling Contractor)."
  },
  {
    id: "rig-038",
    name: "Noble Bob Douglas",
    contractor: "Noble Corporation",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2013,
    region: "South America",
    country: "Guyana",
    lat: 6.8,
    lng: -57.8,
    position: "area",
    statusOverride: null,
    source: "Noble fleet status report, Jul 27, 2026",
    asOf: "2026-07-27",
    contracts: [
      { customer: "ExxonMobil", start: "Apr 2018", end: "Feb 2029", dayRate: null, firmness: "firm", note: "market-based rate under the ExxonMobil Commercial Enabling Agreement, reset each Jan 1 and Jul 1" }
    ],
    note: "ExxonMobil Guyana development drilling under the Commercial Enabling Agreement, to Feb 2029. Market-based rate, not disclosed; it resets each Jan 1 and Jul 1."
  },
  {
    id: "rig-039",
    name: "Noble Tom Madden",
    contractor: "Noble Corporation",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2014,
    region: "South America",
    country: "Guyana",
    lat: 7.2,
    lng: -57.2,
    position: "area",
    statusOverride: null,
    source: "Noble fleet status report, Jul 27, 2026; Drilling Contractor, Sep 28, 2026",
    asOf: "2026-09-28",
    contracts: [
      { customer: "ExxonMobil", start: "Dec 2019", end: "Feb 2029", dayRate: null, firmness: "firm", note: "market-based rate under the ExxonMobil Commercial Enabling Agreement, reset each Jan 1 and Jul 1" }
    ],
    note: "ExxonMobil Guyana development drilling under the Commercial Enabling Agreement, to Feb 2029. Market-based rate, not disclosed. Resumed at the Whiptail WT_1i11 well on Sep 26, 2026, with drilling due to finish Oct 31 (Drilling Contractor)."
  },
  {
    id: "rig-040",
    name: "Noble Don Taylor",
    contractor: "Noble Corporation",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2013,
    region: "South America",
    country: "Guyana",
    lat: 6.5,
    lng: -57,
    position: "area",
    statusOverride: null,
    source: "Noble fleet status report, Jul 27, 2026",
    asOf: "2026-07-27",
    contracts: [
      { customer: "ExxonMobil", start: "Nov 2019", end: "Feb 2029", dayRate: null, firmness: "firm", note: "market-based rate under the ExxonMobil Commercial Enabling Agreement, reset each Jan 1 and Jul 1" }
    ],
    note: "ExxonMobil Guyana under the Commercial Enabling Agreement, to Feb 2029. Market-based rate, not disclosed; it resets each Jan 1 and Jul 1."
  },
  {
    id: "rig-041",
    name: "Noble BlackHornet",
    contractor: "Noble Corporation",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2014,
    region: "Gulf of America",
    country: "United States",
    lat: 28,
    lng: -88,
    position: "area",
    statusOverride: null,
    source: "Noble fleet status report, Jul 27, 2026",
    asOf: "2026-07-27",
    contracts: [
      { customer: "bp", start: "Feb 2025", end: "Feb 2027", dayRate: null, firmness: "firm", note: "two years, ~$350M" },
      { customer: "bp", start: "Feb 2027", end: "Feb 2029", dayRate: null, firmness: "firm", note: "two-year extension, ~$310M excl. MPD" },
      { customer: "bp", start: "Feb 2029", end: "Feb 2030", dayRate: null, firmness: "option", note: "one-year priced option" }
    ],
    note: "bp US Gulf: current two-year contract (~$350M) to Feb 2027, then a two-year extension (~$310M excl. MPD, awarded Oct 2025) to Feb 2029, plus a one-year priced option. Day rate not disclosed."
  },
  {
    id: "rig-042",
    name: "Noble BlackLion",
    contractor: "Noble Corporation",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2014,
    region: "Gulf of America",
    country: "United States",
    lat: 27.6,
    lng: -88.5,
    position: "area",
    statusOverride: null,
    source: "Noble fleet status report, Jul 27, 2026",
    asOf: "2026-07-27",
    contracts: [
      { customer: "bp", start: "Sep 2024", end: "Sep 2026", dayRate: null, firmness: "firm", note: "two years, ~$350M" },
      { customer: "bp", start: "Sep 2026", end: "Sep 2028", dayRate: null, firmness: "firm", note: "two-year extension, ~$310M excl. MPD" },
      { customer: "bp", start: "Sep 2028", end: "Sep 2029", dayRate: null, firmness: "option", note: "one-year priced option" }
    ],
    note: "bp US Gulf: two-year contract (~$350M) Sep 2024 to Sep 2026, then a two-year extension (~$310M excl. MPD, awarded Oct 2025) running Sep 2026 to Sep 2028, plus a one-year priced option. Day rate not disclosed."
  },
  {
    id: "rig-043",
    name: "Noble BlackRhino",
    contractor: "Noble Corporation",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2013,
    region: "Gulf of America",
    country: "United States",
    lat: 27.2,
    lng: -89.3,
    position: "area",
    statusOverride: null,
    source: "rig-tracker reporting, early Oct 2026",
    asOf: "2026-10",
    contracts: [],
    note: "Beacon Offshore Energy US Gulf workover program (one firm well from Mar 2026 plus the ~100-day option well from Apr 2026) wrapped up ~early Aug 2026 per rig-tracker reporting. No follow-on contract announced through early Oct 2026; available in the US Gulf."
  },
  {
    id: "rig-044",
    name: "Noble Gerry de Souza",
    contractor: "Noble Corporation",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2015,
    region: "West Africa",
    country: "Nigeria",
    lat: 3.9,
    lng: 7.6,
    position: "area",
    statusOverride: null,
    source: "Esso/ExxonMobil, Aug 2026",
    asOf: "2026-08-20",
    contracts: [
      { customer: "ExxonMobil", start: "Aug 2026", end: "Aug 2028", dayRate: null, firmness: "firm", note: "Usan Infill Project; ~$292M plus up to three years of options" }
    ],
    note: "Arrived at the Usan field (OML 138, offshore Akwa Ibom) ~Aug 20, 2026 for Esso/ExxonMobil's ~$1B Usan Infill Project (an eight-well campaign per Esso). Two-year contract via the PIDWAL JV, ~$292M plus up to three years of options. Day rate not disclosed."
  },
  {
    id: "rig-045",
    name: "Noble Developer",
    contractor: "Noble Corporation",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2009,
    region: "South America",
    country: "Suriname",
    lat: 6.8,
    lng: -55.3,
    position: "area",
    statusOverride: null,
    source: "Noble fleet status report, Jul 27, 2026",
    asOf: "2026-07-27",
    contracts: [
      { customer: "Petronas", start: "Jul 2025", end: "Sep 2026", dayRate: null, firmness: "firm", note: "Suriname" },
      { customer: "ExxonMobil", start: "Oct 2026", end: "Nov 2026", dayRate: 375000, firmness: "firm", note: "Guyana, one well (~50 days), ~$22M incl. mob/demob" },
      { customer: "bp", start: "Dec 2026", end: "Aug 2027", dayRate: 375000, firmness: "firm", note: "Trinidad, three wells plus three unpriced option wells" }
    ],
    note: "DSS-21 DP semisubmersible (ex-Maersk Developer). The Jul 27, 2026 FSR shows a Petronas Suriname job to Sep 2026, then one ExxonMobil Guyana well (Oct to Nov 2026, $375k/day), then a three-well bp Trinidad program (Dec 2026 to Aug 2027, $375k/day). A 120-180 day Shell contract (~$70M) listed in the Jan and Apr FSRs no longer appears; management called the change a resequencing and gave no further reason."
  },
  {
    id: "rig-046",
    name: "Noble Endeavor",
    contractor: "Noble Corporation",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2013,
    region: "South America",
    country: null,
    lat: 10.5,
    lng: -61,
    position: "area",
    statusOverride: null,
    source: "Noble fleet status report, Jul 27, 2026",
    asOf: "2026-07-27",
    contracts: [
      { customer: null, start: "Jan 2027", end: "Jun 2028", dayRate: 300000, firmness: "firm", note: "11 wells, South America; plus performance bonus and mob/demob fees" }
    ],
    note: "11-well contract with an undisclosed operator in South America at $300,000/day plus mob/demob and performance-incentive upside (Jan 26, 2026 awards release). The Jul 27, 2026 FSR moved the start to Jan 2027 (from Dec 2026) and shows it running to Jun 2028."
  },
  {
    id: "rig-047",
    name: "Noble Claus Bachmann (ex Noble GreatWhite)",
    contractor: "Noble Corporation",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2016,
    region: "North Sea",
    country: "Norway",
    lat: 60.2,
    lng: 3.5,
    position: "area",
    statusOverride: null,
    source: "Noble fleet status report, Jul 27, 2026; Drilling Contractor, Jun 9, 2026",
    asOf: "2026-07-27",
    contracts: [
      { customer: "bp", start: "Mar 2027", end: "Sep 2027", dayRate: 320000, firmness: "firm", note: "UK, three wells (150-210 days), plus $5M mobilization fee" },
      { customer: "Aker BP", start: "Sep 2027", end: "Sep 2030", dayRate: null, firmness: "firm", note: "three years, ~$473M incl. mobilization" }
    ],
    note: "Moss CS-60E harsh-environment semisubmersible (built 2016), renamed from Noble GreatWhite in Jun 2026. Being reactivated (~$160M) for a three-well bp UK program (Mar to Sep 2027, $320k/day), then Noble's Norwegian market entry: a three-year Aker BP contract (Sep 2027 to Sep 2030, ~$473M incl. mobilization, excl. integrated services and bonus). Aker BP day rate not disclosed."
  },
  {
    id: "rig-048",
    name: "Noble Venturer",
    contractor: "Noble Corporation",
    owner: null,
    type: "Drillship",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1000,
    buildYear: 2014,
    region: "West Africa",
    country: "Ghana",
    lat: 5.2,
    lng: -1.5,
    position: "area",
    statusOverride: null,
    source: "Noble fleet status report, Jul 27, 2026",
    asOf: "2026-07-27",
    contracts: [
      { customer: "Planet One", start: "Dec 2026", end: "Feb 2027", dayRate: 430000, firmness: "firm", note: "one well (~45 days), two unpriced option wells" },
      { customer: "Amni", start: "Feb 2027", end: "Mar 2027", dayRate: 450000, firmness: "firm", note: "one exploration well" },
      { customer: "Shell", start: "Q4 2027", end: "Q3 2031", dayRate: null, firmness: "firm", note: "US Gulf, four years, ~$606M base plus up to 20% performance pay; four 1-year options" }
    ],
    note: "Tullow's Ghana Jubilee campaign ran to Sep 2026. Next: a Planet One Ghana well (Dec 2026 to Feb 2027, $430k/day, two unpriced option wells), an Amni Ghana exploration well (Feb to Mar 2027, $450k/day), then a four-year Shell US Gulf contract from Q4 2027 to Q3 2031 (~$606M base plus up to 20% performance pay, four one-year options), per the Jul 27, 2026 FSR."
  },
  {
    id: "rig-049",
    name: "Bestla (ex Noble Resolute)",
    contractor: "Borr Drilling",
    owner: null,
    type: "Jackup",
    generation: null,
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 350,
    hookload_tons: 600,
    buildYear: 2008,
    region: "North Sea",
    country: "Netherlands",
    lat: 52.5,
    lng: 3.8,
    position: "area",
    statusOverride: null,
    source: "Borr fleet status report, Aug 2026; update, Sep 2026",
    asOf: "2026-09",
    contracts: [
      { customer: "Eni", start: "Dec 2025", end: "Dec 2026", dayRate: 125000, firmness: "firm" },
      { customer: "Eni", start: "Jan 2027", end: "Sep 2027", dayRate: null, firmness: "firm", note: "exercised nine-month option; a further nine-month option remains" }
    ],
    note: "Sold to Borr Drilling in the five-jackup package that closed Jan 28, 2026 and renamed Bestla; Noble operates it under a bareboat charter until Borr assumes operations in Q4 2026. Eni exercised a nine-month option in the Netherlands extending the contract to Sep 2027, with a further nine-month fixed-price option (Borr Aug 2026 FSR / Sep 2026 update). $125k/day is the original rate; option-period rate undisclosed."
  },
  {
    id: "rig-050",
    name: "Noble Interceptor",
    contractor: "Noble Corporation",
    owner: null,
    type: "Jackup",
    generation: null,
    jackupClass: null,
    environment: "Ultra-Harsh",
    waterDepth_ft: 492,
    hookload_tons: 600,
    buildYear: 2014,
    region: "North Sea",
    country: "Norway",
    lat: 56.28,
    lng: 3.39,
    position: "field",
    statusOverride: null,
    source: "ConocoPhillips award, Aug 2026",
    asOf: "2026-08",
    contracts: [
      { customer: "Aker BP", start: "Sep 2026", end: "Feb 2027", dayRate: null, firmness: "firm", note: "Valhall accommodation, $38.7M incl. mob/demob" },
      { customer: "ConocoPhillips", start: "Q3 2027", end: "Q2 2029", dayRate: null, firmness: "firm", note: "Greater Ekofisk P&A, 670 days" }
    ],
    note: "Aker BP 150-day accommodation scope ($38.7M incl. mob/demob, up to 90 days of options) at Valhall supporting the PWP-Fenris offshore completion, ~Sep 2026 to Feb 2027. ConocoPhillips then awarded a 670-day Greater Ekofisk P&A contract from Q3 2027 (announced Aug 2026). Day rate not disclosed."
  },
  {
    id: "rig-051",
    name: "VALARIS DS-7",
    contractor: "Valaris",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 10000,
    hookload_tons: 1250,
    buildYear: 2013,
    region: "West Africa",
    country: "Angola",
    lat: -7.2,
    lng: 12.5,
    position: "area",
    statusOverride: null,
    source: "Valaris fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Azule Energy", start: "Jun 2024", end: "Oct 2026", dayRate: null, firmness: "firm", note: "~850 days, ~$364M" },
      { customer: "Azule Energy", start: "Oct 2026", end: "Sep 2027", dayRate: null, firmness: "firm", note: "five wells, ~325 days, ~$125M" },
      { customer: "Azule Energy", start: "Oct 2027", end: "Q3 2028", dayRate: null, firmness: "option", note: "five-well unpriced option, est. 300-350 days; dates estimated" }
    ],
    note: "Azule Energy, Angola. The current program (from Jun 2024, ~$364M over ~850 days) runs to Oct 2026, then a five-well firm extension to Sep 2027 (~325 days, ~$125M), plus a five-well unpriced option of an estimated 300-350 days. Day rate undisclosed (Aug 5, 2026 FSR)."
  },
  {
    id: "rig-052",
    name: "VALARIS DS-8",
    contractor: "Valaris",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2015,
    region: "South America",
    country: "Brazil",
    lat: -24,
    lng: -43,
    position: "area",
    statusOverride: null,
    source: "Valaris fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Petrobras", start: "Dec 2023", end: "Dec 2026", dayRate: 428000, firmness: "firm" },
      { customer: "Shell", start: "Mar 2027", end: "May 2029", dayRate: null, firmness: "firm", note: "~800 days, ~$300M, ~1 year of options" }
    ],
    note: "Petrobras Brazil Dec 2023-Dec 2026 at $428,000/day plus ~$30M mobilization fee. Next: Shell Brazil Mar 2027-May 2029 (~$300M over ~800 days, ~1 year of options) after ~60 days out of service for upgrades in 1Q27 (Aug 5, 2026 FSR)."
  },
  {
    id: "rig-053",
    name: "VALARIS DS-9",
    contractor: "Valaris",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2015,
    region: "West Africa",
    country: "Angola",
    lat: -8,
    lng: 12.8,
    position: "area",
    statusOverride: null,
    source: "Valaris fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "ExxonMobil", start: "Jul 2026", end: "Jul 2028", dayRate: null, firmness: "firm", note: "two 6-month options" }
    ],
    note: "ExxonMobil (Esso Exploration Angola); two-year extension Jul 2026 to Jul 2028 in direct continuation, with MPD services and two 6-month options. The day rate is described only as in line with recent market rates in the region. About 15 days out of service for maintenance expected in Q2 2027. On continuous ExxonMobil Angola hire since Jul 2022."
  },
  {
    id: "rig-054",
    name: "VALARIS 121",
    contractor: "Valaris",
    owner: null,
    type: "Jackup",
    generation: null,
    jackupClass: "Modern",
    environment: "Harsh",
    waterDepth_ft: 400,
    hookload_tons: 1250,
    buildYear: 2014,
    region: "North Sea",
    country: "United Kingdom",
    lat: 57.5,
    lng: 1.2,
    position: "area",
    statusOverride: null,
    source: "Valaris fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Adura", start: "Feb 2026", end: "Nov 2026", dayRate: null, firmness: "firm", note: "one option of ~150-200 days" }
    ],
    note: "Adura (Shell/Equinor UK JV); current firm term Feb 2026-Nov 2026 (per Aug 5, 2026 FSR), >$25M backlog on ~194 days; one option of ~150-200 days. Prior term Jan 2025-Jan 2026 (~$55M). Day rate undisclosed."
  },
  {
    id: "rig-055",
    name: "VALARIS Norway",
    contractor: "Valaris",
    owner: null,
    type: "Jackup",
    generation: null,
    jackupClass: null,
    environment: "Ultra-Harsh",
    waterDepth_ft: 400,
    hookload_tons: 1000,
    buildYear: 2011,
    region: "North Sea",
    country: "United Kingdom",
    lat: 58,
    lng: 1.8,
    position: "area",
    statusOverride: null,
    source: "Valaris fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Ithaca Energy", start: "May 2026", end: "Feb 2027", dayRate: null, firmness: "firm" }
    ],
    note: "Ithaca Energy, UK (harsh-environment jackup); current extension May 2026-Feb 2027 with contracted revenue backlog of ~$36M based on duration of 300 days; prior firm term Apr 2025-May 2026 (TCV ~$39M, 292 days). Day rate undisclosed."
  },
  {
    id: "rig-056",
    name: "VALARIS 106",
    contractor: "Valaris",
    owner: null,
    type: "Jackup",
    generation: null,
    jackupClass: "Modern",
    environment: null,
    waterDepth_ft: 400,
    hookload_tons: 750,
    buildYear: 2005,
    region: "Asia Pacific",
    country: "Indonesia",
    lat: -3.5,
    lng: 117,
    position: "area",
    statusOverride: null,
    source: "Valaris fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "bp", start: "Oct 2026", end: "Sep 2028", dayRate: null, firmness: "firm", note: "eight wells, ~2 years, ~$74M" }
    ],
    note: "BP Indonesia 8-well contract (~2 years, ~$74M, four 1-well options), expected to start late 3Q/4Q26 after ~90 days out of service for leg repairs (Aug 5, 2026 FSR). The interim Medco Energi one-well job was terminated by mutual agreement. Day rate undisclosed."
  },
  {
    id: "rig-057",
    name: "VALARIS 248",
    contractor: "Valaris",
    owner: null,
    type: "Jackup",
    generation: null,
    jackupClass: "Modern",
    environment: "Ultra-Harsh",
    waterDepth_ft: 400,
    hookload_tons: 1000,
    buildYear: 2000,
    region: "North Sea",
    country: "United Kingdom",
    lat: 56,
    lng: 1.5,
    position: "area",
    statusOverride: null,
    source: "Valaris fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "GE Vernova", start: "Nov 2025", end: "Sep 2026", dayRate: null, firmness: "firm", note: "offshore wind accommodation support, incl. 101-day extension" },
      { customer: null, start: "Apr 2027", end: "Mar 2030", dayRate: null, firmness: "firm", note: "41-well P&A, ~1,080 days, ~$140M" }
    ],
    note: "GE Vernova offshore-wind accommodation work ended ~Sep 2026 and the Eni East Irish Sea contract was reassigned to VALARIS 120 (Aug 5, 2026 FSR). Next: 41-well UK North Sea P&A contract, Apr 2027 to Mar 2030 in the fleet status table (mid-2027 in its summary), ~1,080 days, ~$140M with annual escalation and two unpriced 1-year options; customer undisclosed."
  },
  {
    id: "rig-058",
    name: "Deepsea Stavanger",
    contractor: "Odfjell Drilling",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2010,
    region: "North Sea",
    country: "Norway",
    lat: 61.8,
    lng: 4.2,
    position: "area",
    statusOverride: null,
    source: "Odfjell Drilling Q2 2026 report, Aug 18, 2026",
    asOf: "2026-08-18",
    contracts: [
      { customer: "Aker BP", start: "Q1 2025", end: "Q2 2030", dayRate: null, firmness: "firm", note: "five years, base value $620-730M" }
    ],
    note: "Aker BP five-year Yggdrasil firm contract (including the Munin production wells) from early 2025 to ~Q2 2030, following earlier Aker BP frame work; base value $620-730M. The day rate is market-based within a pre-agreed range, set by brokers each year. 99% financial utilization in Q2 2026. Harsh-environment Tier 1 semisub."
  },
  {
    id: "rig-059",
    name: "Deepsea Nordkapp",
    contractor: "Odfjell Drilling",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2019,
    region: "North Sea",
    country: "Norway",
    lat: 62.3,
    lng: 5,
    position: "area",
    statusOverride: null,
    source: "Aker BP extension, Jul 17, 2026",
    asOf: "2026-07-17",
    contracts: [
      { customer: "Aker BP", start: "2024", end: "End 2028", dayRate: null, firmness: "firm" }
    ],
    note: "Aker BP NCS since 2019 delivery. Jul 17, 2026: Aker BP confirmed a further one-year firm extension taking backlog to end-2028, with further options. Extension rate to be set by two independent brokers by end-2026; undisclosed."
  },
  {
    id: "rig-060",
    name: "Deepsea Aberdeen",
    contractor: "Odfjell Drilling",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2014,
    region: "North Sea",
    country: "Norway",
    lat: 60,
    lng: 2.5,
    position: "area",
    statusOverride: null,
    source: "Odfjell Drilling Q2 2026 report, Aug 18, 2026",
    asOf: "2026-08-18",
    contracts: [
      { customer: "Equinor", start: "Q4 2025", end: "Q3 2026", dayRate: null, firmness: "firm", note: "eight-well option, ~$121M" },
      { customer: "Equinor", start: "Q4 2026", end: "Q1 2029", dayRate: null, firmness: "firm", note: "~$373M firm; interim NCS scope, then Fram Sør" }
    ],
    note: "Equinor NCS: an eight-well extension (~$121M) ran from Q4 2025 to Q3 2026, followed in direct continuation by a new contract signed Dec 19, 2025 (~$373M firm, excl. integrated services, bonuses, fuel incentives and escalation): an interim NCS scope, then the Fram Sør development, Q4 2026 to Q1 2029. No release has yet confirmed the new contract started."
  },
  {
    id: "rig-061",
    name: "Deepsea Atlantic",
    contractor: "Odfjell Drilling",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2009,
    region: "North Sea",
    country: "United Kingdom",
    lat: 61,
    lng: -3.8,
    position: "area",
    statusOverride: null,
    source: "Odfjell Drilling Q2 2026 report, Aug 18, 2026",
    asOf: "2026-08-18",
    contracts: [
      { customer: "Adura", start: "2022", end: "Q2 2027", dayRate: null, firmness: "firm" }
    ],
    note: "Owned (not managed) rig working the Rosebank development west of Shetland for Adura (contract signed with Equinor). Off hire from Apr 18, 2026 after its BOP dropped to the seabed; back on rate Aug 2, 2026 after 106 days, with $82M of insurance income. Contract to end Q2 2027 (Jan 2025 extension, ~$148M) with four priced one-well options and three ~1-year optional periods at rates to be agreed."
  },
  {
    id: "rig-062",
    name: "Deepsea Bergen (ex Bollsta)",
    contractor: "Odfjell Drilling",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2016,
    region: "North Sea",
    country: "Norway",
    lat: 60.7,
    lng: 2.9,
    position: "area",
    statusOverride: null,
    source: "Vår Energi award, Sep 10, 2026",
    asOf: "2026-09-10",
    contracts: [
      { customer: "Equinor", start: "Dec 2025", end: "Q1 2028", dayRate: null, firmness: "firm" },
      { customer: "Vår Energi", start: "Early 2028", end: "Q1 2031", dayRate: null, firmness: "loi", note: "3-year letter of award, ~$518M incl. mob" }
    ],
    note: "Renamed Deepsea Bergen after Odfjell's USD 480M purchase from Northern Ocean (Dec 2025). Novated Equinor NCS contract firm to Q1 2028 (~USD 355M). Sep 10, 2026: Var Energi awarded a 3-year LOA from early 2028 in direct continuation (~USD 518M incl. mob), extending firm backlog to Q1 2031. Day rates undisclosed."
  },
  {
    id: "rig-063",
    name: "Santorini",
    contractor: "Saipem",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2008,
    region: "Mediterranean & Black Sea",
    country: null,
    lat: 33.2,
    lng: 34,
    position: "area",
    statusOverride: null,
    source: "Saipem release, Jul 22, 2026",
    asOf: "2026-07-22",
    contracts: [
      { customer: "Eni", start: "Q1 2027", end: null, dayRate: null, firmness: "firm", note: "Côte d'Ivoire, Baleine Phase 3, ~$260M; term undisclosed" }
    ],
    note: "On Eni East Mediterranean work (term undisclosed) at the Jul 22, 2026 award of a ~USD 260M Eni Cote d'Ivoire contract: long-term Baleine Phase 3 development drilling from early 2027, with options and possible work in neighbouring countries (Saipem release). Planned maintenance was pulled into 2026 for a clean start (H1 2026 results)."
  },
  {
    id: "rig-064",
    name: "Deep Value Driller",
    contractor: "Ventura Offshore",
    owner: "Eldorado Drilling",
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2014,
    region: "Asia Pacific",
    country: "Indonesia",
    lat: -4.3,
    lng: 133,
    position: "area",
    statusOverride: null,
    source: "Ventura Offshore release, Sep 4, 2026; sale completed Sep 10, 2026",
    asOf: "2026-09-10",
    contracts: [
      { customer: "PETRONAS", start: "Oct 2026", end: null, dayRate: null, firmness: "firm", note: "one well, ~$58M incl. provisional sums; start and duration not confirmed" }
    ],
    note: "Bareboat-chartered to Saipem from 2023. Eldorado Drilling's $300M offer beat Saipem's agreed purchase in Feb 2026, and the sale from Deep Value Driller AS completed Sep 10, 2026. Ventura Offshore markets and operates the rig for Eldorado and signed a one-well contract (~$58M incl. provisional sums) with PETRONAS E&P Bobara for an ultra-deepwater exploration well in the Bobara PSC, offshore West Papua, Indonesia. Trade press names the well Redha-1 and reported a hoped-for spud by Oct 2026; no start has been confirmed."
  },
  {
    id: "rig-065",
    name: "Scarabeo 9",
    contractor: "Saipem",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2011,
    region: "West Africa",
    country: "Ghana",
    lat: 3.6,
    lng: -2.5,
    position: "area",
    statusOverride: null,
    source: "Saipem H1 2026 results; AIS, Jul 2026",
    asOf: "2026-07",
    contracts: [],
    note: "Eni Libya campaign ended early 2026; Saipem's H1 2026 results cite lower activity and maintenance in 2026, with the rig in tenders and advanced talks for West Africa work. AIS (Jul 2026) showed it heading for Takoradi, Ghana; no new contract announced as of early Oct 2026."
  },
  {
    id: "rig-066",
    name: "Stena Carron",
    contractor: "Stena Drilling",
    owner: null,
    type: "Drillship",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2011,
    region: "South America",
    country: "Guyana",
    lat: 7.6,
    lng: -56.6,
    position: "area",
    statusOverride: null,
    source: "MARAD, Aug 2026",
    asOf: "2026-08",
    contracts: [
      { customer: "ExxonMobil", start: "2025", end: "Dec 2026", dayRate: null, firmness: "firm" }
    ],
    note: "Sole Stena drillship in Guyana's Stabroek Block; ExxonMobil/Esso extension (signed Jul 2025) runs to Dec 31, 2026 with options. After Goby-1 it drilled the Rockhead-1 exploration well (~213 km offshore), due to finish by end-Aug 2026 per MARAD. No 2027 extension announced yet."
  },
  {
    id: "rig-067",
    name: "Stena DrillMAX",
    contractor: "Stena Drilling",
    owner: null,
    type: "Drillship",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2010,
    region: "South America",
    country: "Suriname",
    lat: 6.6,
    lng: -54.6,
    position: "area",
    statusOverride: null,
    source: "Stena Drilling release, Apr 15, 2026",
    asOf: "2026-04-15",
    contracts: [
      { customer: "TotalEnergies / Shell", start: "2025", end: "End 2025", dayRate: null, firmness: "firm", note: "Suriname: TotalEnergies one well (Macaw-1), Shell two wells" },
      { customer: "TotalEnergies / Shell", start: "Jan 2026", end: "2026", dayRate: null, firmness: "option", note: "options into 2026; exercise not confirmed" },
      { customer: "Energean", start: "Early 2027", end: null, dayRate: null, firmness: "firm", note: "Greece, Block 2, one well with MPD" }
    ],
    note: "Drilled Suriname wells for TotalEnergies (Macaw-1 from Jun 2025, plus up to three option wells) and Shell (two firm plus two option wells). Stena's last fleet update (Aug 7, 2025) showed firm work to end-2025 with options into 2026; no 2026 source confirms the options were exercised. Next: one firm well for Energean in Greece's Block 2 (NW Ionian Sea) from early 2027, Greece's first deepwater well (Stena release, Apr 15, 2026)."
  },
  {
    id: "rig-068",
    name: "Stena IceMAX",
    contractor: "Stena Drilling",
    owner: null,
    type: "Drillship",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2012,
    region: "Mediterranean & Black Sea",
    country: "Egypt",
    lat: 31,
    lng: 30.5,
    position: "area",
    statusOverride: null,
    source: "Stena release, Aug 18, 2026",
    asOf: "2026-08-18",
    contracts: [
      { customer: null, start: "Aug 2026", end: null, dayRate: null, firmness: "firm" }
    ],
    note: "Completed Shell's Egypt campaign ahead of schedule with 99.5% uptime (Stena release, ~Aug 18, 2026): both Mina West development wells completed and tested, and Velox-1X (2,810 m water depth, the Mediterranean's deepest) reached TD early with oil indicators (Egypt petroleum ministry, Jul 24, 2026). Stena said the rig moved directly to a new, undisclosed client in the region."
  },
  {
    id: "rig-069",
    name: "Stena Don",
    contractor: "Stena Drilling",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 5000,
    hookload_tons: 600,
    buildYear: 2001,
    region: "North Sea",
    country: "United Kingdom",
    lat: 58.5,
    lng: 0.5,
    position: "area",
    statusOverride: null,
    source: "Drilling Contractor, Aug 13, 2025",
    asOf: "2025-08-13",
    contracts: [
      { customer: null, start: "Feb 2026", end: "Dec 2026", dayRate: null, firmness: "firm", note: "four wells, ~10 months; up to 24 months of options" }
    ],
    note: "Four-well firm UK campaign (~10 months) from Feb 2026 for an undisclosed operator, with up to 24 months of options (to end-2028 if all are exercised). The previous customer was Shell UK, whose UK assets moved to Adura on Dec 1, 2025, so Adura is plausible, but no source names it. Named Shell's Floating Rig of the Year 2025."
  },
  {
    id: "rig-070",
    name: "COSL Innovator",
    contractor: "COSL",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 7500,
    hookload_tons: 750,
    buildYear: 2012,
    region: "North Sea",
    country: "Norway",
    lat: 60.4,
    lng: 2.8,
    position: "area",
    statusOverride: null,
    source: "Havtil consent, Sep 24, 2026",
    asOf: "2026-09-24",
    contracts: [
      { customer: "Equinor", start: "Q2 2025", end: "Q2 2027", dayRate: null, firmness: "firm", note: "up to 3 years of options" }
    ],
    note: "On a 2-year firm Equinor NCS contract (Q2 2025-Q2 2027) with up to 3 years of options. 2026 Sodir permits name it for wildcats 34/10-56 S, 16/4-14 and 25/9-5 S (Grane prospect); Havtil consent for 25/9-5 S came Sep 24, 2026, with drilling expected Nov 2026."
  },
  {
    id: "rig-071",
    name: "COSL Promoter",
    contractor: "COSL",
    owner: null,
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 7500,
    hookload_tons: 750,
    buildYear: 2012,
    region: "North Sea",
    country: "Norway",
    lat: 61.5,
    lng: 3.5,
    position: "area",
    statusOverride: null,
    source: "Havtil consent, Aug 25, 2026",
    asOf: "2026-08-25",
    contracts: [
      { customer: "Equinor", start: "Q1 2025", end: "Q1 2026", dayRate: null, firmness: "firm" },
      { customer: "Equinor", start: "Q2 2026", end: "2026", dayRate: null, firmness: "option", note: "apparently on exercised options; term not disclosed" }
    ],
    note: "Works for Equinor on the NCS (2023 award: 1-year firm from Q1 2025 plus up to 4 years of options) and remains active past the firm year, apparently on exercised options. 2026 Havtil consents: permanent P&A of Tordis well 34/7-K-4 HT2 (Jun) and production drilling at Fram Ost (Aug 25, 2026)."
  },
  {
    id: "rig-072",
    name: "Deepsea Mira",
    contractor: "Odfjell Drilling",
    owner: "Northern Ocean",
    type: "Semisubmersible",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2019,
    region: "West Africa",
    country: "Namibia",
    lat: -22.9,
    lng: 14.1,
    position: "area",
    statusOverride: null,
    source: "Northern Ocean release, early Oct 2026",
    asOf: "2026-10",
    contracts: [
      { customer: "Shell", start: "Apr 2027", end: "Q3 2027", dayRate: null, firmness: "firm", note: "Trinidad and Tobago, ~150 days, ~$70M; 1-year option" }
    ],
    note: "Shell Namibia (PEL 39) contract ended Jul 2, 2026, followed by ~30 days in Walvis Bay upgrading the drilling control system. Early Oct 2026: Northern Ocean signed a Shell contract for Trinidad and Tobago / the wider Caribbean - ~150 days firm from Apr 2027 (~$70M incl. mob/demob) plus a 1-year option (up to ~$226M total). Day rate undisclosed."
  },
  {
    id: "rig-073",
    name: "Borr Odin",
    contractor: "Borr Drilling",
    owner: null,
    type: "Jackup",
    generation: null,
    jackupClass: "Modern Premium",
    environment: null,
    waterDepth_ft: 400,
    hookload_tons: 450,
    buildYear: 2019,
    region: "Gulf of America",
    country: "United States",
    lat: 28.4,
    lng: -95.3,
    position: "area",
    statusOverride: null,
    source: "Borr release, Sep 15, 2026",
    asOf: "2026-09-15",
    contracts: [
      { customer: null, start: "Sep 2026", end: "Dec 2026", dayRate: null, firmness: "firm" },
      { customer: "Cantium", start: "Feb 2027", end: "Jul 2027", dayRate: null, firmness: "firm", note: "with options" }
    ],
    note: "Mobilized offshore Texas mid-Aug 2026 and began a two-well firm contract for an undisclosed operator, on dayrate from Sep 11, 2026 (Borr release Sep 15, 2026), expected to end Dec 2026. The Cantium contract now runs Feb-Jul 2027 with options (Aug 11, 2026 FSR). Day rate not disclosed."
  },
  {
    id: "rig-074",
    name: "Borr Ran",
    contractor: "Borr Drilling",
    owner: null,
    type: "Jackup",
    generation: null,
    jackupClass: "Modern Premium",
    environment: null,
    waterDepth_ft: 400,
    hookload_tons: 450,
    buildYear: 2019,
    region: "Gulf of America",
    country: "Mexico",
    lat: 19.9,
    lng: -92.8,
    position: "area",
    statusOverride: "Unconfirmed",
    source: "Borr fleet status report, Aug 11, 2026",
    asOf: "2026-08-11",
    contracts: [
      { customer: "Eni", start: "May 2025", end: "Sep 2026", dayRate: null, firmness: "firm" }
    ],
    note: "Eni Mexico campaign extended to Sep 2026 (listed under New Contracts/Extensions: 'Extension: April 2026 to September 2026, Eni (Mexico)'); day rate not disclosed. The Aug 11, 2026 fleet status report still lists the rig operating for Eni to Sep 2026; no extension or follow-on found as of Oct 4, 2026, so its current status is unconfirmed."
  },
  {
    id: "rig-075",
    name: "Borr Saga",
    contractor: "Borr Drilling",
    owner: null,
    type: "Jackup",
    generation: null,
    jackupClass: "Modern Premium",
    environment: null,
    waterDepth_ft: 400,
    hookload_tons: 450,
    buildYear: 2019,
    region: "Asia Pacific",
    country: "Brunei",
    lat: 5.3,
    lng: 114.3,
    position: "area",
    statusOverride: null,
    source: "Borr fleet status report, Aug 11, 2026",
    asOf: "2026-08-11",
    contracts: [
      { customer: "Brunei Shell Petroleum", start: "Nov 2022", end: "Apr 2027", dayRate: null, firmness: "firm", note: "with options to extend" }
    ],
    note: "Long-running Brunei Shell Petroleum contract offshore Brunei, with options to extend (FSR status: 'Operating with option to extend'); day rate not disclosed."
  },
  {
    id: "rig-076",
    name: "Borr Idun",
    contractor: "Borr Drilling",
    owner: null,
    type: "Jackup",
    generation: null,
    jackupClass: "Modern Premium",
    environment: null,
    waterDepth_ft: 400,
    hookload_tons: 450,
    buildYear: 2020,
    region: "Asia Pacific",
    country: "Vietnam",
    lat: 10.3,
    lng: 107.9,
    position: "area",
    statusOverride: null,
    source: "Borr release, Sep 15, 2026",
    asOf: "2026-09-15",
    contracts: [
      { customer: "Hoang Long JOC", start: "Sep 2026", end: "Oct 2026", dayRate: null, firmness: "firm" },
      { customer: "PVEP", start: "Oct 2026", end: "Feb 2027", dayRate: null, firmness: "firm", note: "three wells, ~130 days" }
    ],
    note: "Back at work in Vietnam from Jul 2026: ~60 days for an undisclosed operator, then one well for Hoang Long JOC (Sep-Oct 2026), per the Aug 11, 2026 FSR. In direct continuation, a three-well ~130-day TL-WHP campaign (Blocks 01/97 & 02/97) for PVEP via PV Drilling from mid-Oct 2026 to ~Feb 2027 (Borr release Sep 15, 2026). Day rate not disclosed."
  },
  {
    id: "rig-077",
    name: "Borr Natt",
    contractor: "Borr Drilling",
    owner: null,
    type: "Jackup",
    generation: null,
    jackupClass: "Modern Premium",
    environment: null,
    waterDepth_ft: 400,
    hookload_tons: 450,
    buildYear: 2020,
    region: "West Africa",
    country: "Nigeria",
    lat: 4.2,
    lng: 5.8,
    position: "area",
    statusOverride: null,
    source: "Borr release, Sep 30, 2026",
    asOf: "2026-09-30",
    contracts: [
      { customer: "SNEPCO", start: "Apr 2026", end: "Aug 2027", dayRate: null, firmness: "firm" }
    ],
    note: "Working for SNEPCO (Shell Nigeria) on the HI gas field since late Apr 2026; on Sep 30, 2026 SNEPCO exercised a one-well option keeping the rig contracted into early Aug 2027 (Borr release). Day rate not disclosed."
  },
  {
    id: "rig-078",
    name: "Borr Gunnlod",
    contractor: "Borr Drilling",
    owner: null,
    type: "Jackup",
    generation: null,
    jackupClass: "Modern Premium",
    environment: null,
    waterDepth_ft: 400,
    hookload_tons: 450,
    buildYear: 2019,
    region: "Asia Pacific",
    country: "Vietnam",
    lat: 8.3,
    lng: 107.8,
    position: "area",
    statusOverride: null,
    source: "Borr fleet status report, Aug 11, 2026",
    asOf: "2026-08-11",
    contracts: [
      { customer: "PVEP", start: "Aug 2026", end: "Apr 2027", dayRate: null, firmness: "firm", note: "six wells; two unpriced one-well options" }
    ],
    note: "TLJOC well ended Jul 2026. Six-well firm PVEP-NCS campaign offshore Vietnam (Nam Con Son area) started Aug 2026, estimated ~8 months to Apr 2027, plus two unpriced one-well options (~110 days combined), per the Aug 11, 2026 FSR. Day rate not disclosed."
  },
  {
    id: "rig-079",
    name: "Borr Njord",
    contractor: "Borr Drilling",
    owner: null,
    type: "Jackup",
    generation: null,
    jackupClass: "Modern Premium",
    environment: null,
    waterDepth_ft: 400,
    hookload_tons: 450,
    buildYear: 2020,
    region: "Gulf of America",
    country: "Mexico",
    lat: 20.3,
    lng: -92.2,
    position: "area",
    statusOverride: null,
    source: "Borr release, Sep 15, 2026",
    asOf: "2026-09-15",
    contracts: [
      { customer: "PEMEX", start: "May 2026", end: "Apr 2028", dayRate: null, firmness: "firm", note: "with extension options" }
    ],
    note: "PEMEX work offshore Mexico May 2026-Apr 2028 with extension options. Sep 15, 2026: Borr agreed to sell its 51% Perfomex JV stake to its local partner, which will operate Njord, Galar and Gersemi; Borr retains the rigs and contract economics via bareboat charters. Day rate not disclosed."
  },
  {
    id: "rig-080",
    name: "Stena Evolution",
    contractor: "Stena Drilling",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2016,
    region: "Gulf of America",
    country: "United States",
    lat: 27,
    lng: -91.5,
    position: "area",
    statusOverride: null,
    source: "Stena Drilling contract release, May 29, 2023",
    asOf: "2023-05-29",
    contracts: [
      { customer: "Shell", start: "Q2 2024", end: "Q2 2029", dayRate: null, firmness: "firm", note: "five-year primary term, then an extension option" }
    ],
    note: "Ultra-deepwater DP3 on a five-year Shell Offshore US Gulf contract from Q2 2024 (to ~Q2 2029, with an extension option); being upgraded with a 20,000-psi BOP from 2026 for Shell's Sparta completions (first oil 2028). Day rate undisclosed."
  },
  {
    id: "rig-081",
    name: "Stena Forth",
    contractor: "Stena Drilling",
    owner: null,
    type: "Drillship",
    generation: "6th Gen",
    jackupClass: null,
    environment: "Harsh",
    waterDepth_ft: 10000,
    hookload_tons: 1000,
    buildYear: 2012,
    region: "Mediterranean & Black Sea",
    country: "Egypt",
    lat: 31.7,
    lng: 33.3,
    position: "area",
    statusOverride: null,
    source: "AIS, Jun 28, 2026",
    asOf: "2026-06-28",
    contracts: [
      { customer: "Chevron", start: "May 2026", end: "2026", dayRate: null, firmness: "firm" }
    ],
    note: "Harsh-environment DP3 drillship. Spudded the Nargis-2 appraisal well for Chevron (with Eni, Mubadala and Tharwa) at the Nargis gas field, East Nile Delta offshore Egypt, ~May 21-23, 2026; AIS (Jun 28, 2026) confirms the East Mediterranean position. Previously operated off West Africa."
  },
  {
    id: "rig-083",
    name: "Tidal Action",
    contractor: "Constellation",
    owner: "Hanwha Drilling",
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2024,
    region: "South America",
    country: "Brazil",
    lat: -22.5,
    lng: -40,
    position: "area",
    statusOverride: null,
    source: "Hanwha Drilling and Petrobras start-up reports, Sep 2025",
    asOf: "2025-09-19",
    contracts: [
      { customer: "Petrobras", start: "Sep 2025", end: "Mar 2028", dayRate: null, firmness: "firm", note: "30-month charter" }
    ],
    note: "7th-gen ultra-deepwater drillship (ex-West Libra) on its ~30-month maiden Petrobras charter at the Roncador field, Campos Basin; operations started Sep 17, 2025. Owned by Hanwha Drilling and operated by Constellation Oil Services (its first third-party-owned drillship), with ~$500M added to Hanwha Drilling's backlog. The Mar 2028 end is estimated from the ~30-month term. Day rate undisclosed."
  },
  {
    id: "rig-084",
    name: "VALARIS DS-16",
    contractor: "Valaris",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2014,
    region: "Gulf of America",
    country: "United States",
    lat: 27.3,
    lng: -91.0,
    position: "area",
    statusOverride: null,
    source: "Valaris fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Occidental", start: "Jun 2024", end: "Jun 2026", dayRate: null, firmness: "firm", note: "MPD at an additional rate" },
      { customer: "Occidental", start: "Jun 2026", end: "Dec 2028", dayRate: null, firmness: "firm", note: "940-day extension; two 1-year options" }
    ],
    note: "Occidental (Anadarko) in the US Gulf of America since Jun 2024; drilled the Bandit discovery near the Constitution field (Green Canyon) in Apr 2026. A 940-day extension to Dec 2028 was signed together with a 914-day contract for VALARIS DS-18, adding about $760M of backlog combined, each with two 1-year options. About 35 days out of service for maintenance expected in Q4 2026. Day rate undisclosed (Aug 5, 2026 FSR)."
  },
  {
    id: "rig-085",
    name: "VALARIS DS-18",
    contractor: "Valaris",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2015,
    region: "Gulf of America",
    country: "United States",
    lat: 27.0,
    lng: -90.3,
    position: "area",
    statusOverride: null,
    source: "Valaris fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: null, start: "Nov 2026", end: "May 2027", dayRate: null, firmness: "loi", note: "two-well exploration program, up to seven months; location undisclosed" },
      { customer: "Occidental", start: "Jun 2027", end: "Dec 2029", dayRate: null, firmness: "firm", note: "914 days; two 1-year options" }
    ],
    note: "Letter of award for a two-well exploration program (operator and location undisclosed) from Nov 2026 for up to seven months, then a 914-day Occidental contract in the US Gulf of America from Jun 2027, moved to follow on directly from the letter-of-award work. Signed with the DS-16 extension for about $760M of backlog combined. Plotted at the Occidental work area; current position unconfirmed. Day rate undisclosed (Aug 5, 2026 FSR)."
  },
  {
    id: "rig-086",
    name: "VALARIS DS-17",
    contractor: "Valaris",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2014,
    region: "South America",
    country: "Brazil",
    lat: -23.0,
    lng: -40.2,
    position: "area",
    statusOverride: null,
    source: "Valaris fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Equinor", start: "Mar 2026", end: "Jan 2028", dayRate: null, firmness: "firm", note: "~852 days incl. 180-day standby; TCV ~$498M; three priced options, 228 days" }
    ],
    note: "Equinor’s Raia gas project (BM-C-33), pre-salt Campos Basin, offshore Rio de Janeiro: drilling started Mar 24, 2026. Estimated value $498M including MPD, additional services, mobilization and minor upgrades, over about 852 days (a 180-day standby period and a 672-day drilling program), with three priced options totalling 228 days. Day rate undisclosed (Aug 5, 2026 FSR)."
  },
  {
    id: "rig-087",
    name: "VALARIS DS-15",
    contractor: "Valaris",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2014,
    region: "West Africa",
    country: "Côte d'Ivoire",
    lat: 4.9,
    lng: -4.45,
    position: "area",
    statusOverride: null,
    source: "Valaris fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "CNR International", start: "Sep 2026", end: "May 2027", dayRate: null, firmness: "firm", note: "~250 days, TCV ~$135M incl. upgrades and mobilization; priced options 80-100 days" }
    ],
    note: "Reactivated from warm stack in Las Palmas, Spain, for CNR International offshore Côte d’Ivoire from Sep 2026: about 250 days valued at about $135M including upfront payments for rig upgrades (an enhanced MPD system) and mobilization, with priced options of 80 to 100 days. Most likely the Baobab field (block CI-40); AIS placed the rig at the Baobab terminal in Aug 2026, but the field is not named by the operator. Day rate undisclosed (Aug 5, 2026 FSR)."
  },
  {
    id: "rig-088",
    name: "VALARIS DS-12",
    contractor: "Valaris",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2013,
    region: "Mediterranean & Black Sea",
    country: "Egypt",
    lat: 31.6,
    lng: 29.9,
    position: "area",
    statusOverride: null,
    source: "Valaris fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "bp", start: "Apr 2026", end: "Apr 2027", dayRate: null, firmness: "firm", note: "~350 days, TCV ~$140M incl. MPD and mobilization; three option wells" }
    ],
    note: "bp (with Arcius) in the West Nile Delta, offshore Egypt, from Apr 2026: about 350 days valued at about $140M including MPD and mobilization, with three option wells. Wells include Fayoum 4, Ghorab and Raven West for bp and Atoll West and Nofret for Arcius. Day rate undisclosed (Aug 5, 2026 FSR)."
  },
  {
    id: "rig-089",
    name: "VALARIS DS-10",
    contractor: "Valaris",
    owner: null,
    type: "Drillship",
    generation: "7th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1250,
    buildYear: 2017,
    region: "West Africa",
    country: "Nigeria",
    lat: 4.55,
    lng: 4.6,
    position: "area",
    statusOverride: null,
    source: "Valaris fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Shell", start: "Jun 2026", end: "Jul 2028", dayRate: null, firmness: "firm", note: "two years, TCV $352M; two 1-year options" }
    ],
    note: "Shell (SNEPCO) at Bonga North, deepwater Nigeria, from Jun 2026: two years valued at $352M excluding additional services, with an additional rate for controlled-mud-level services and two 1-year options. About 45 days out of service for rig upgrades expected in Q1 2027. Day rate undisclosed (Aug 5, 2026 FSR)."
  },
  {
    id: "rig-090",
    name: "VALARIS DS-4",
    contractor: "Valaris",
    owner: null,
    type: "Drillship",
    generation: "6th Gen",
    jackupClass: null,
    environment: null,
    waterDepth_ft: 12000,
    hookload_tons: 1000,
    buildYear: 2010,
    region: "South America",
    country: "Brazil",
    lat: -24.79,
    lng: -42.32,
    position: "field",
    statusOverride: null,
    source: "Valaris fleet status report, Aug 5, 2026",
    asOf: "2026-08-05",
    contracts: [
      { customer: "Petrobras", start: "Dec 2024", end: "Nov 2027", dayRate: null, firmness: "firm", note: "incl. MPD and additional services; ~$41M mobilization fee" },
      { customer: "Petrobras", start: "Nov 2027", end: "Oct 2030", dayRate: null, firmness: "firm", note: "1,064-day extension, ~$447M" }
    ],
    note: "Petrobras at the Búzios field, pre-salt Santos Basin, since Dec 2024, then a 1,064-day extension to Oct 2030 (about $447M of backlog). The previous $450,000 day rate has been adjusted down, reducing backlog by about $21M; the new rate is undisclosed (Aug 5, 2026 FSR)."
  }
];
