#!/usr/bin/env node
/* Builds basemap.js (the bundled world outline the map draws) from Natural Earth.
   Natural Earth is public domain: https://www.naturalearthdata.com/

     curl -LO https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson
     node scripts/build-basemap.js ne_50m_admin_0_countries.geojson

   Output format, per country: n = name, p = label point [lng, lat], z = lowest zoom
   at which Natural Earth suggests labelling it, g = rings. Each ring is a flat list
   of integers in hundredths of a degree: the first lng/lat pair, then deltas. */
const fs = require('fs');
const path = require('path');

const src = process.argv[2];
if (!src) { console.error('Usage: node scripts/build-basemap.js <ne_50m_admin_0_countries.geojson>'); process.exit(1); }
const geo = JSON.parse(fs.readFileSync(src, 'utf8'));
const SKIP = ['Antarctica']; // far outside the map's bounds, and badly stretched by the projection

function encodeRing(ring) {
  const out = [];
  let px = 0, py = 0, points = 0;
  ring.forEach(function (pt) {
    const x = Math.round(pt[0] * 100), y = Math.round(pt[1] * 100);
    if (points && x === px && y === py) return;
    out.push(x - px, y - py);
    px = x; py = y; points++;
  });
  return points >= 4 ? out : null;
}

let vertices = 0;
const countries = geo.features
  .filter(f => !SKIP.includes(f.properties.NAME))
  .map(function (f) {
    const polys = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates;
    const rings = [];
    polys.forEach(poly => poly.forEach(function (ring) {
      const enc = encodeRing(ring);
      if (enc) { rings.push(enc); vertices += enc.length / 2; }
    }));
    const p = f.properties;
    return {
      n: p.NAME,
      p: [Math.round(p.LABEL_X * 100) / 100, Math.round(p.LABEL_Y * 100) / 100],
      z: p.MIN_LABEL,
      g: rings
    };
  })
  .filter(c => c.g.length)
  .sort((a, b) => a.n.localeCompare(b.n));

const out = '/* Generated by scripts/build-basemap.js from Natural Earth 1:50m countries (public domain). Do not edit by hand. */\n' +
  'window.BASEMAP = {"countries":[\n' + countries.map(c => JSON.stringify(c)).join(',\n') + '\n]};\n';
const dest = path.join(__dirname, '..', 'basemap.js');
fs.writeFileSync(dest, out);
console.log(countries.length + ' countries, ' + vertices + ' points, ' + Math.round(out.length / 1024) + ' KB -> ' + path.relative(process.cwd(), dest));
